
//----------------------------------------------------
// The following code was generated by CUP v0.11a beta 20060608
// Thu Sep 17 08:15:54 CST 2015
//----------------------------------------------------

package interpreter.analizador;

/** CUP generated class containing symbol constants. */
public class sym {
  /* terminals */
  public static final int DISPLAY = 20;
  public static final int CHAR = 26;
  public static final int DATETIME = 28;
  public static final int INTEGER = 24;
  public static final int STATUS = 18;
  public static final int PUNTOCOMA = 9;
  public static final int UPDATE = 52;
  public static final int ASTERISCO = 6;
  public static final int DELETE = 53;
  public static final int WHERE = 42;
  public static final int IS = 47;
  public static final int ALTER = 33;
  public static final int NOT = 30;
  public static final int IGUAL = 4;
  public static final int REFERENCES = 37;
  public static final int GET = 17;
  public static final int ON = 39;
  public static final int FOREIGN = 36;
  public static final int VARCHAR = 27;
  public static final int NUM = 57;
  public static final int SELECT = 40;
  public static final int MIN = 50;
  public static final int DATABASES = 15;
  public static final int ID = 59;
  public static final int EOF = 0;
  public static final int DECIMAL = 25;
  public static final int GROUP = 43;
  public static final int PALABRA = 58;
  public static final int BY = 44;
  public static final int TABLE = 22;
  public static final int error = 1;
  public static final int LIKE = 46;
  public static final int COMA = 8;
  public static final int VALUES = 56;
  public static final int NEWLINE = 10;
  public static final int ADD = 34;
  public static final int NULL = 29;
  public static final int MENOR = 3;
  public static final int JOIN = 45;
  public static final int START = 16;
  public static final int FROM = 41;
  public static final int MAYOR = 2;
  public static final int INTO = 55;
  public static final int CONSTRAINT = 35;
  public static final int INDEX = 38;
  public static final int STOP = 19;
  public static final int INSERT = 54;
  public static final int CREATE = 11;
  public static final int LIST = 14;
  public static final int DROP = 13;
  public static final int DATABASE = 12;
  public static final int KEY = 32;
  public static final int AVERAGE = 49;
  public static final int COUNT = 48;
  public static final int AS = 23;
  public static final int ABRIRPAR = 5;
  public static final int PRIMARY = 31;
  public static final int MAX = 51;
  public static final int SET = 21;
  public static final int CERRARPAR = 7;
}

